USE saproject;
# Roles
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("BA", True, "Business Analysis");
SET @BA_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("SCM", True, "Scum Master");
SET @SCM_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("PO", True, "Project Owner");
SET @PO_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("UI DES", True, "UI Designer");
SET @UI_DES_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("UX DES", True, "Ux Designer");
SET @UX_DES_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("DEV", True, "Developer");
SET @DEV_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("QA", True, "Quality Assurance");
SET @QA_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("WTR", True, "Project Watcher");
SET @WTR_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("AYS", True, "Anonymous users, has the lowest permission");
SET @AYS_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("SPU", True, "Super User, All permissions in system.");
SET @SPU_pk=@@IDENTITY;
INSERT INTO sa_t_role (`name`, enable, description) VALUES ("STU", True, "Stuff User, Has the permission to access System Administartion Page.");
SET @STU_pk=@@IDENTITY;

 # Site Client
INSERT INTO sa_t_site_client (`name`, description, `client_id`, `security_key`, `scope`, `enable`,created_time) VALUES ("frontend", "That's a frontend", "U11hRx68gSQkdhmEqo4YIGrrV8zJaCu3H5q3UKU17dI", "VTExaFJ4NjhnU1FrZGhtRXFvNFlJR3JyVjh6SmFDdTNINXEzVUtVMTdkSQ", "all", True, "2013-07-22 10:33:14.999000" );
SET @site_client_id=@@IDENTITY;

 # Users
INSERT INTO sa_t_user (`username`,`password`, last_login, first_name, last_name, email, is_staff, is_active, date_joined, site_client_id, update_time, last_edited_by, birthday) VALUES ("userpo", "pbkdf2_sha256$10000$xAj4T44sD3J2$mVMAuvzGa8Tz/tgfCIrjIWySD7RczWIrX7cBPQhvwe0=", "2013-07-22 10:33:16.079000", "userpo", "XIAO", "test0@test.com", False, True, "2013-07-22 10:33:16.079000", @site_client_id, "2013-07-22 10:33:16.078000", "admin", "1983-06-15T00:00");
SET @userpo_pk=@@IDENTITY;
INSERT INTO sa_t_user (`username`,`password`, last_login, first_name, last_name, email, is_staff, is_active, date_joined, site_client_id, update_time, last_edited_by, birthday) VALUES ("userdev", "pbkdf2_sha256$10000$xAj4T44sD3J2$mVMAuvzGa8Tz/tgfCIrjIWySD7RczWIrX7cBPQhvwe0=", "2013-07-22 10:33:16.079000", "userdev", "XIAO", "test1@test.com", False, True, "2013-07-22 10:33:16.079000", @site_client_id, "2013-07-22 10:33:16.078000", "admin", "1983-06-15T00:00");
SET @userdev_pk=@@IDENTITY;
INSERT INTO sa_t_user (`username`,`password`, last_login, first_name, last_name, email, is_staff, is_active, date_joined, site_client_id, update_time, last_edited_by, birthday) VALUES ("userqa", "pbkdf2_sha256$10000$xAj4T44sD3J2$mVMAuvzGa8Tz/tgfCIrjIWySD7RczWIrX7cBPQhvwe0=", "2013-07-22 10:33:16.079000", "userqa", "XIAO", "test2@test.com", False, True, "2013-07-22 10:33:16.079000", @site_client_id, "2013-07-22 10:33:16.078000", "admin", "1983-06-15T00:00");
SET @userqa_pk=@@IDENTITY;
SELECT @userpo_pk=id FROM sa_t_user WHERE `username`="userpo";
INSERT INTO sa_t_projects (`name`, alias, owner_id, description, is_private, update_time, last_edited_by) VALUES ("ASPP", "A Sample Project Only For Test", @userpo_pk, "No Descriptions.",  False, "2013-07-22 10:33:16.079000", "admin");

SET @project_pk=@@IDENTITY;

# endpoint
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement/{attachement-name}", "api.project.views.workitem_attachement_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comments", "api.project.views.workitem_comments_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/auth/site-client/{client-id}", "api.auth.views.site_client_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/roles", "api.secure.views.roles_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workflow", "api.project.views.workflow_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/release-archive/{release-version}", "api.project.views.release_archive_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog/{worklog-id}", "api.project.views.workitem_worklog_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog-own/{worklog-id}", "api.project.views.workitem_worklog_own_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project-status/{project-name}", "api.project.views.project_status_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement/{attachment-name}", "api.project.views.workitem_attachement_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/project/{project-name}/users", "api.secure.views.project_users_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}", "api.project.views.project_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog-importance/{catalog-name}", "api.project.views.catalog_importance_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}/user-story", "api.project.views.catalog_user_story_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignee", "api.project.views.assignee_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/release", "api.project.views.release_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comments-own", "api.project.views.workitem_comments_own_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachements", "api.project.views.workitem_attachements_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem-status/{workitem-key}", "api.project.views.workitem_status_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement", "api.project.views.workitem_attachement_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/auth/site-clients", "api.auth.views.site_clients_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/roles/{role-name}/permissions", "api.secure.views.roles_permissions_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment", "api.project.views.workitem_comment_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignable-user", "api.project.views.assignable_user_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalogs", "api.project.views.catalogs_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/user", "api.secure.views.user_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/role/{role-name}", "api.secure.views.role_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment-own/{comment-id}", "api.project.views.workitem_comment_own_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/user/{username}", "api.secure.views.user_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/{project-name}/project-user-role/{username}", "api.secure.views.project_user_role_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/project/{project-id}", "api.project.views.projects_all_pub_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/linkedissues", "api.project.views.workitem_linkedissues_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/secure/project/{project-name}/project-user-role/{username}", "api.secure.views.project_user_role_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}", "api.project.views.workitem_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project", "api.project.views.project_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/projects-all", "api.project.views.projects_all_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/release-schedule/{release-version}", "api.project.views.release_schedule_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-owner-username}/projects", "api.project.views.projects_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem", "api.project.views.workitem_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog", "api.project.views.workitem_worklog_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/release-workitem/{release-name}/workitem/{workitem-key}", "api.project.views.release_workitem_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog-moving/{catalog-name}", "api.project.views.catalog_moving_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement-own/{attachement-name}", "api.project.views.workitem_attachement_own_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklogs", "api.project.views.workitem_worklogs_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog", "api.project.views.catalog_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/projects", "api.project.views.projects_all_pub_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/auth/site-client", "api.auth.views.site_client_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment/{comment-id}", "api.project.views.workitem_comment_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignable-users", "api.project.views.assignable_users_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog-workitem/{catalog-name}/workitem/{workitem-key}", "api.project.views.catalog_workitem_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/releases", "api.project.views.releases_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}", "api.project.views.catalog_view");
INSERT INTO sa_t_endpoint (`name`, codename) VALUES ("{host}/api/owner/{owner-username}/project/{project-name}/release/{release-name}", "api.project.views.release_view");

# permission
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog-moving/{catalog-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Move Catalog", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog-importance/{catalog-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Set Catalog Importance", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Browse Project by Owner", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release/{release-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Release", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comments-own" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete All Own Comments", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/{project-name}/project-user-role/{username}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Unassign User Project Role", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/auth/site-client/{client-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify SiteClient", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog/{worklog-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Worklog", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}/user-story" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify User Story", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/roles/{role-name}/permissions" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Role Permission List", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachements" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete All Attachments", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignable-user" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Assignable User", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignable-users" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Assignable Users", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/role/{role-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Role", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/user/{username}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View User", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/linkedissues" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Link Workitem", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/user/{username}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify User", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/auth/site-client/{client-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete SiteClient", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/projects" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Browse Projects (PUBLIC)", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/assignee" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Assign Workitem", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release-schedule/{release-version}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Schedule Release", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify Projects by Owner", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}/user-story" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Write User Story", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workflow" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View (Read-Only) Workflow", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comments" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete All Comments", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release-workitem/{release-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Include Release", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/roles" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Role List", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/auth/site-client" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create SiteClient", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog-workitem/{catalog-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("exclude Catalog", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment/{comment-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Comment", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Catalog", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Edit Workitem", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/project/{project-name}/users" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View User List by Project", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create Project by Owner", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Log on Workitem", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/projects-all" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Browse Projects (PUBLIC or PRIVATE)", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment-own/{comment-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Own Comment", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/auth/site-clients" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View SiteClient List", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog/{worklog-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Edit Worklog", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment/{comment-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Edit Comment", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment-own/{comment-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Edit Own Comment", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/auth/site-client/{client-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View SiteClient", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog-own/{worklog-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Own Worklogs", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement/{attachement-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Attachment", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/project/{project-name}/project-user-role/{username}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Assign User Project Role", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release-workitem/{release-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("exclude Release", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement/{attachment-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Attachement", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}/user-story" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete User Story", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/project/{project-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify Project", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SPU_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comments" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View All Comments", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/secure/user" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create User", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create Release", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklogs" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete All Worklogs", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-owner-username}/projects" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Browse Projects by Owner", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/releases" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Project's Release", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/comment" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Add Comment", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release/{release-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify Release", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement-own/{attachement-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Own Attachment", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachements" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View All Attachement", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Delete Project by Owner", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/attachement" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create Attachment", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog-workitem/{catalog-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Include Catalog", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem-status/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Set Workitem Status", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@BA_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UI_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@UX_DES_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@QA_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("CreateWorkitem", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@DEV_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project-status/{project-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Set Project Status", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Workitem", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/release-archive/{release-version}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Archive Release", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("DeleteWorkitem", @endpoint_pk, 1);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalogs" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("View Project's Catalogs", @endpoint_pk, 8);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@AYS_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/workitem/{workitem-key}/worklog-own/{worklog-id}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Edit Own Worklogs", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog/{catalog-name}" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Modify Catalog", @endpoint_pk, 2);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );
SET @endpoint_pk=(SELECT id FROM sa_t_endpoint WHERE `name` = "{host}/api/owner/{owner-username}/project/{project-name}/catalog" limit 1);
INSERT INTO sa_t_permission (`name`, endpoint_id, GPPD) VALUES ("Create Catalog", @endpoint_pk, 4);
SET @permission_pk=@@IDENTITY;
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@PO_pk, @permission_pk );
INSERT INTO sa_t_role_permission (role_id, permission_id) VALUES (@SCM_pk, @permission_pk );

 # project user role
INSERT INTO sa_t_project_user_role (project_id, role_id, user_id) VALUES (@project_pk, @PO_pk, @userpo_pk);
INSERT INTO sa_t_project_user_role (project_id, role_id, user_id) VALUES (@project_pk, @DEV_pk, @userdev_pk);
INSERT INTO sa_t_project_user_role (project_id, role_id, user_id) VALUES (@project_pk, @QA_pk, @userqa_pk);
